### ISSUE TITLE
BIOS pull error OMEN 15 DC-1007tx

### ISSUE THREAD

**Issue by xb00ze** [OmenMon/OmenMon#59]
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
OmenMon.Hardware.Bios.BiosException: BIOS call failed: Command not available
   at OmenMon.Hardware.Bios.Bios.Check(Int32 code, Boolean force)
   at OmenMon.Hardware.Bios.BiosCtl.GetMaxFan()
   at OmenMon.Library.Hw.<>c__DisplayClass13_0`1.<BiosGet>b__0(IBiosCtl bios)
   at OmenMon.AppGui.GuiFormMain.UpdateFanCtl()
   at OmenMon.AppGui.GuiFormMain.UpdateAll()
   at OmenMon.AppGui.GuiFormMain..ctor()
   at OmenMon.AppGui.GuiTray.ShowFormMain()
   at OmenMon.AppGui.GuiTray.EventIconMouseClick(Object sender, MouseEventArgs e)
   at System.Windows.Forms.NotifyIcon.OnMouseClick(MouseEventArgs mea)
   at System.Windows.Forms.NotifyIcon.WmMouseUp(Message& m, MouseButtons button)
   at System.Windows.Forms.NotifyIcon.WndProc(Message& msg)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4250.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
OmenMon
    Assembly Version: 0.61.1.0
    Win32 Version: 0.61.1.5021
    CodeBase: file:///C:/Users/xb00ze/Desktop/OmenMon-0.61.1-Release/OmenMon.exe
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4200.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4250.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4190.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4220.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
Microsoft.Management.Infrastructure
    Assembly Version: 1.0.0.0
    Win32 Version: 10.0.19041.1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.Management.Infrastructure/v4.0_1.0.0.0__31bf3856ad364e35/Microsoft.Management.Infrastructure.dll
----------------------------------------
Microsoft.Management.Infrastructure.Native
    Assembly Version: 1.0.0.0
    Win32 Version: 10.0.19041.1 (WinBuild.160101.0800)
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/Microsoft.Management.Infrastructure.Native/v4.0_1.0.0.0__31bf3856ad364e35/Microsoft.Management.Infrastructure.Native.dll
----------------------------------------
Microsoft.Management.Infrastructure.UserFilteredExceptionHandling
    Assembly Version: 0.0.0.0
    Win32 Version: 10.0.19041.1 (WinBuild.160101.0800)
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/Microsoft.Management.Infrastructure.Native/v4.0_1.0.0.0__31bf3856ad364e35/Microsoft.Management.Infrastructure.Native.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by xb00ze** [comment]
System Specs :=
Product name (Model)	OMEN by HP Laptop 15-dc1xxx
Product number (SKU)	6JP29PA#ACJ
Software build ID	19WW1GMT601#SACJ#DACJ
Motherboard ID	8574
BIOS Version	F.29
BIOS Internal Version	HPQOEM - 1072009
BIOS Build Date	12-12-2023
BIOS Manufacturer	AMI
Keyboard (Baseboard) version	21.17
Keyboard (Baseboard) SN	PHUTH018JBV0GQ
Total memory	32635 M
Processor name	Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
System Family	103C_5335KV HP OMEN
Feature Byte	#3K6b7B7W8AaBaHapaqarawbAbhdUdXdpdqfPfdhZhw.mT
OMEN Feature	SystemInfo, NetworkBooster, FourZone, PerformanceControl
OMEN Background Feature	NetworkBooster, FourZone, PerformanceControl
OMEN Product Number	8574, 8575, 860A, 87B5

Windows Version 10.0.19042 Build 19042
SMBIOS Version	3.2

**Comment by xb00ze** [comment]
Disabling the  BIOS report in XML file makes the application a bit frugal, since OGH lite already can do the bare minimum.
