### ISSUE TITLE
HP OMEN AC Adaptor causes unknown BIOS call 4

### ISSUE THREAD

**Issue by vazome** [OmenMon/OmenMon#82]
I get an error whenever I connect my stock power adapter. At first, I thought that the issue may be caused by HDR. I checked without HDR and the issue persists.

**System Information:**
```
------------------
System Information
------------------
      Time of this report: 11/30/2024, 22:27:11
             Machine name: HP-OMEN-G14
               Machine Id: {B5390C91-BEB8-4542-97E3-9E5CE2310933}
         Operating System: Windows 11 Home 64-bit (10.0, Build 26100) (26100.ge_release.240331-1435)
                 Language: English (Regional Setting: English)
      System Manufacturer: HP
             System Model: OMEN Transcend Gaming Laptop 14-fb0xxx
                     BIOS: F.07 (type: UEFI)
                Processor: Intel(R) Core(TM) Ultra 7 155H (22 CPUs), ~3.8GHz
                   Memory: 16384MB RAM
      Available OS Memory: 15800MB RAM
                Page File: 13401MB used, 26974MB available
              Windows Dir: C:\WINDOWS
          DirectX Version: DirectX 12
      DX Setup Parameters: Not found
         User DPI Setting: 192 DPI (200 percent)
       System DPI Setting: 192 DPI (200 percent)
          DWM DPI Scaling: UnKnown
                 Miracast: Available, with HDCP
Microsoft Graphics Hybrid: Supported
 DirectX Database Version: 1.6.3
   Auto Super Res Version: Unknown
       System Mux Support: Mux Support Inactive - Ok
           Mux Target GPU: dGPU
           DxDiag Version: 10.00.26100.2161 64bit Unicode
```

**The Error:**
```See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
OmenMon.Hardware.Bios.BiosException: BIOS call failed: Unknown response from BIOS: 4
   at OmenMon.Hardware.Bios.Bios.Check(Int32 code, Boolean force)
   at OmenMon.Hardware.Bios.BiosCtl.GetAdapter()
   at OmenMon.Library.Hw.<>c__DisplayClass13_0`1.<BiosGet>b__0(IBiosCtl bios)
   at OmenMon.AppGui.GuiFormMain.UpdateSys()
   at OmenMon.AppGui.GuiFormMain.UpdateAll()
   at OmenMon.AppGui.GuiFormMain..ctor()
   at OmenMon.AppGui.GuiTray.ShowFormMain()
   at OmenMon.AppGui.GuiTray.EventIconMouseClick(Object sender, MouseEventArgs e)
   at System.Windows.Forms.NotifyIcon.OnMouseClick(MouseEventArgs mea)
   at System.Windows.Forms.NotifyIcon.WmMouseUp(Message& m, MouseButtons button)
   at System.Windows.Forms.NotifyIcon.WndProc(Message& msg)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9282.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
OmenMon
    Assembly Version: 0.61.1.0
    Win32 Version: 0.61.1.5021
    CodeBase: file:///C:/Users/danie/Documents/OmenMon.exe
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9282.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9256.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9277.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
Microsoft.Management.Infrastructure
    Assembly Version: 1.0.0.0
    Win32 Version: 10.0.26100.1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Microsoft.Management.Infrastructure/v4.0_1.0.0.0__31bf3856ad364e35/Microsoft.Management.Infrastructure.dll
----------------------------------------
Microsoft.Management.Infrastructure.Native
    Assembly Version: 1.0.0.0
    Win32 Version: 10.0.26100.1 (WinBuild.160101.0800)
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/Microsoft.Management.Infrastructure.Native/v4.0_1.0.0.0__31bf3856ad364e35/Microsoft.Management.Infrastructure.Native.dll
----------------------------------------
Microsoft.Management.Infrastructure.UserFilteredExceptionHandling
    Assembly Version: 0.0.0.0
    Win32 Version: 10.0.26100.1 (WinBuild.160101.0800)
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/Microsoft.Management.Infrastructure.Native/v4.0_1.0.0.0__31bf3856ad364e35/Microsoft.Management.Infrastructure.Native.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.
```

**Comment by cheslijones** [comment]
Hi, any solution for this? I'm running into the same issue on the same laptop:

- Tried HP AC adapter 
- Tried Ankor AC adapter
- Not plugged into any AC adapter the application works fine
- As soon as either AC adapter is plugged in, regardless of port, the errors start popping up if the OmenMon GUI is open
- Basically, have to unplug the laptop, set settings in the OmenMon GUI, close the OmenMon GUI, and then reconnect the AC adapter
